// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Auto-generated Linux Libnotify bindings for Dart
class NotifyBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NotifyBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NotifyBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<NotifyNotification> notify_notification_new(
    ffi.Pointer<ffi.Char> summary,
    ffi.Pointer<ffi.Char> body,
    ffi.Pointer<ffi.Char> icon,
  ) {
    return _notify_notification_new(summary, body, icon);
  }

  late final _notify_notification_newPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<NotifyNotification> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('notify_notification_new');
  late final _notify_notification_new = _notify_notification_newPtr
      .asFunction<
        ffi.Pointer<NotifyNotification> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  int notify_notification_show(
    ffi.Pointer<NotifyNotification> notification,
    ffi.Pointer<ffi.Pointer<GError>> error,
  ) {
    return _notify_notification_show(notification, error);
  }

  late final _notify_notification_showPtr =
      _lookup<
        ffi.NativeFunction<
          gboolean Function(
            ffi.Pointer<NotifyNotification>,
            ffi.Pointer<ffi.Pointer<GError>>,
          )
        >
      >('notify_notification_show');
  late final _notify_notification_show = _notify_notification_showPtr
      .asFunction<
        int Function(
          ffi.Pointer<NotifyNotification>,
          ffi.Pointer<ffi.Pointer<GError>>,
        )
      >();

  int notify_init(ffi.Pointer<ffi.Char> app_name) {
    return _notify_init(app_name);
  }

  late final _notify_initPtr =
      _lookup<ffi.NativeFunction<gboolean Function(ffi.Pointer<ffi.Char>)>>(
        'notify_init',
      );
  late final _notify_init = _notify_initPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  void notify_uninit() {
    return _notify_uninit();
  }

  late final _notify_uninitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('notify_uninit');
  late final _notify_uninit = _notify_uninitPtr.asFunction<void Function()>();
}

final class _NotifyNotification extends ffi.Struct {
  external GObject parent_object;

  external ffi.Pointer<NotifyNotificationPrivate> priv;
}

typedef GObject = _GObject;

final class _GObject extends ffi.Struct {
  external GTypeInstance g_type_instance;

  @guint()
  external int ref_count;

  external ffi.Pointer<GData> qdata;
}

typedef GTypeInstance = _GTypeInstance;

final class _GTypeInstance extends ffi.Struct {
  external ffi.Pointer<GTypeClass> g_class;
}

typedef GTypeClass = _GTypeClass;

final class _GTypeClass extends ffi.Struct {
  @GType()
  external int g_type;
}

typedef GType = gsize;
typedef gsize = ffi.UnsignedLong;
typedef Dartgsize = int;
typedef guint = ffi.UnsignedInt;
typedef Dartguint = int;
typedef GData = _GData;

final class _GData extends ffi.Opaque {}

typedef NotifyNotificationPrivate = _NotifyNotificationPrivate;

final class _NotifyNotificationPrivate extends ffi.Opaque {}

final class _NotifyNotificationClass extends ffi.Struct {
  external GObjectClass parent_class;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<NotifyNotification> notification)
    >
  >
  closed;
}

typedef GObjectClass = _GObjectClass;

final class _GObjectClass extends ffi.Struct {
  external GTypeClass g_type_class;

  external ffi.Pointer<GSList> construct_properties;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<GObject> Function(
        GType type,
        guint n_construct_properties,
        ffi.Pointer<GObjectConstructParam> construct_properties,
      )
    >
  >
  constructor;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<GObject> object,
        guint property_id,
        ffi.Pointer<GValue> value,
        ffi.Pointer<GParamSpec> pspec,
      )
    >
  >
  set_property;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<GObject> object,
        guint property_id,
        ffi.Pointer<GValue> value,
        ffi.Pointer<GParamSpec> pspec,
      )
    >
  >
  get_property;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GObject> object)>
  >
  dispose;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GObject> object)>
  >
  finalize;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<GObject> object,
        guint n_pspecs,
        ffi.Pointer<ffi.Pointer<GParamSpec>> pspecs,
      )
    >
  >
  dispatch_properties_changed;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<GObject> object,
        ffi.Pointer<GParamSpec> pspec,
      )
    >
  >
  notify;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GObject> object)>
  >
  constructed;

  @gsize()
  external int flags;

  @gsize()
  external int n_construct_properties;

  external gpointer pspecs;

  @gsize()
  external int n_pspecs;

  @ffi.Array.multi([3])
  external ffi.Array<gpointer> pdummy;
}

typedef GSList = _GSList;

final class _GSList extends ffi.Struct {
  external gpointer data;

  external ffi.Pointer<GSList> next;
}

typedef gpointer = ffi.Pointer<ffi.Void>;
typedef GObjectConstructParam = _GObjectConstructParam;

final class _GObjectConstructParam extends ffi.Struct {
  external ffi.Pointer<GParamSpec> pspec;

  external ffi.Pointer<GValue> value;
}

typedef GParamSpec = _GParamSpec;

final class _GParamSpec extends ffi.Struct {
  external GTypeInstance g_type_instance;

  external ffi.Pointer<gchar> name;

  @ffi.Int()
  external int flagsAsInt;

  GParamFlags get flags => GParamFlags.fromValue(flagsAsInt);

  @GType()
  external int value_type;

  @GType()
  external int owner_type;

  external ffi.Pointer<gchar> _nick;

  external ffi.Pointer<gchar> _blurb;

  external ffi.Pointer<GData> qdata;

  @guint()
  external int ref_count;

  @guint()
  external int param_id;
}

typedef gchar = ffi.Char;
typedef Dartgchar = int;

enum GParamFlags {
  G_PARAM_READABLE(1),
  G_PARAM_WRITABLE(2),
  G_PARAM_READWRITE(3),
  G_PARAM_CONSTRUCT(4),
  G_PARAM_CONSTRUCT_ONLY(8),
  G_PARAM_LAX_VALIDATION(16),
  G_PARAM_STATIC_NAME(32),
  G_PARAM_STATIC_NICK(64),
  G_PARAM_STATIC_BLURB(128),
  G_PARAM_EXPLICIT_NOTIFY(1073741824),
  G_PARAM_DEPRECATED(-2147483648);

  static const G_PARAM_PRIVATE = G_PARAM_STATIC_NAME;

  final int value;
  const GParamFlags(this.value);

  static GParamFlags fromValue(int value) => switch (value) {
    1 => G_PARAM_READABLE,
    2 => G_PARAM_WRITABLE,
    3 => G_PARAM_READWRITE,
    4 => G_PARAM_CONSTRUCT,
    8 => G_PARAM_CONSTRUCT_ONLY,
    16 => G_PARAM_LAX_VALIDATION,
    32 => G_PARAM_STATIC_NAME,
    64 => G_PARAM_STATIC_NICK,
    128 => G_PARAM_STATIC_BLURB,
    1073741824 => G_PARAM_EXPLICIT_NOTIFY,
    -2147483648 => G_PARAM_DEPRECATED,
    _ => throw ArgumentError("Unknown value for GParamFlags: $value"),
  };

  @override
  String toString() {
    if (this == G_PARAM_STATIC_NAME)
      return "GParamFlags.G_PARAM_STATIC_NAME, GParamFlags.G_PARAM_PRIVATE";
    return super.toString();
  }
}

typedef GValue = _GValue;

final class _GValue extends ffi.Struct {
  @GType()
  external int g_type;

  @ffi.Array.multi([2])
  external ffi.Array<UnnamedUnion1> data;
}

final class UnnamedUnion1 extends ffi.Union {
  @gint()
  external int v_int;

  @guint()
  external int v_uint;

  @glong()
  external int v_long;

  @gulong()
  external int v_ulong;

  @gint64()
  external int v_int64;

  @guint64()
  external int v_uint64;

  @gfloat()
  external double v_float;

  @gdouble()
  external double v_double;

  external gpointer v_pointer;
}

typedef gint = ffi.Int;
typedef Dartgint = int;
typedef glong = ffi.Long;
typedef Dartglong = int;
typedef gulong = ffi.UnsignedLong;
typedef Dartgulong = int;
typedef gint64 = ffi.Long;
typedef Dartgint64 = int;
typedef guint64 = ffi.UnsignedLong;
typedef Dartguint64 = int;
typedef gfloat = ffi.Float;
typedef Dartgfloat = double;
typedef gdouble = ffi.Double;
typedef Dartgdouble = double;
typedef NotifyNotification = _NotifyNotification;

enum NotifyUrgency {
  NOTIFY_URGENCY_LOW(0),
  NOTIFY_URGENCY_NORMAL(1),
  NOTIFY_URGENCY_CRITICAL(2);

  final int value;
  const NotifyUrgency(this.value);

  static NotifyUrgency fromValue(int value) => switch (value) {
    0 => NOTIFY_URGENCY_LOW,
    1 => NOTIFY_URGENCY_NORMAL,
    2 => NOTIFY_URGENCY_CRITICAL,
    _ => throw ArgumentError("Unknown value for NotifyUrgency: $value"),
  };
}

enum NotifyClosedReason {
  NOTIFY_CLOSED_REASON_UNSET(-1),
  NOTIFY_CLOSED_REASON_EXPIRED(1),
  NOTIFY_CLOSED_REASON_DISMISSED(2),
  NOTIFY_CLOSED_REASON_API_REQUEST(3),
  NOTIFY_CLOSED_REASON_UNDEFIEND(4);

  final int value;
  const NotifyClosedReason(this.value);

  static NotifyClosedReason fromValue(int value) => switch (value) {
    -1 => NOTIFY_CLOSED_REASON_UNSET,
    1 => NOTIFY_CLOSED_REASON_EXPIRED,
    2 => NOTIFY_CLOSED_REASON_DISMISSED,
    3 => NOTIFY_CLOSED_REASON_API_REQUEST,
    4 => NOTIFY_CLOSED_REASON_UNDEFIEND,
    _ => throw ArgumentError("Unknown value for NotifyClosedReason: $value"),
  };
}

typedef gboolean = gint;

/// GError:
/// @domain: error domain, e.g. %G_FILE_ERROR
/// @code: error code, e.g. %G_FILE_ERROR_NOENT
/// @message: human-readable informative error message
///
/// The `GError` structure contains information about
/// an error that has occurred.
typedef GError = _GError;

final class _GError extends ffi.Struct {
  @GQuark()
  external int domain;

  @gint()
  external int code;

  external ffi.Pointer<gchar> message;
}

typedef GQuark = guint32;
typedef guint32 = ffi.UnsignedInt;
typedef Dartguint32 = int;

const int NOTIFY_EXPIRES_DEFAULT = -1;

const int NOTIFY_EXPIRES_NEVER = 0;

const int NOTIFY_VERSION_MAJOR = 0;

const int NOTIFY_VERSION_MINOR = 8;

const int NOTIFY_VERSION_MICRO = 3;
